name: build-check

on:
  pull_request:
  workflow_call:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: go vet
        run: |
          go vet -v ./...

      - name: go test
        run: |
          go test -v ./...

      - name: Build
        run: go build . && rm miniweb
