name: build-check

on:
  pull_request:
  workflow_call:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0
      - name: Install dependencies
        run: |
          go version
          GO111MODULE=off go get -u golang.org/x/lint/golint
      - name: Lint and check
        run: |
          golint ./...
          go vet ./...
