name: goreleaser

on:
  push:
    tags:
      - "*"

jobs:
  build-and-check:
    uses: kemokemo/miniweb/.github/workflows/build-check.yml@main
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
